# Generated by Django 5.1.1 on 2024-10-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del propietario')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido del propietario')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad del propietario')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion del propietarip')),
                ('telefono', models.CharField(max_length=100, verbose_name='Telefono del propietario')),
                ('correo', models.CharField(max_length=100, verbose_name='Correco del propietario')),
                ('contraseña', models.CharField(max_length=100, verbose_name='Contraseña del propietario')),
                ('activo', models.BooleanField(default=True, verbose_name='Usuario activo')),
            ],
        ),
    ]
