# Generated by Django 5.1.1 on 2024-10-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_app', '0007_continente_pais_provincia_municipio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del instructor')),
                ('profesion', models.CharField(max_length=100, verbose_name='Profesion del instructor')),
                ('especialidad', models.CharField(max_length=100, verbose_name='Especialida  del instructor')),
                ('fecha_contratacion', models.DateField(verbose_name='Fceha de contratacion del instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del aprendiz')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido del aprendiz')),
                ('instructores', models.ManyToManyField(related_name='aprendices', to='primer_app.instructor')),
            ],
        ),
    ]
