# Generated by Django 5.1.1 on 2024-10-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_app', '0003_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='tipo_persona',
            field=models.CharField(choices=[(0, 'Natural'), (1, 'Juridica')], default='Natural', help_text='Igrese si es persona natural y juridica', max_length=20, verbose_name='Tipo de persona'),
        ),
    ]
