# Generated by Django 5.1.1 on 2024-10-11 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_app', '0004_persona_tipo_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del cliente')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo del cliente')),
            ],
        ),
        migrations.CreateModel(
            name='pedido_cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField()),
                ('valor_pedido', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pedidos', to='primer_app.cliente')),
            ],
        ),
    ]
