# Generated by Django 5.1.1 on 2024-10-11 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_app', '0006_usuario_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Continente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=45, verbose_name='Codigo del coontinente')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre del continente')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=45, verbose_name='Codigo del pais')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre del pais')),
                ('continente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Codigo_continente', to='primer_app.continente')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=45, verbose_name='Codigo de la provincia')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre de la provincia')),
                ('pais_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Codigo_provincia', to='primer_app.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=45, verbose_name='Codigo del municipio')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre del municipio')),
                ('municipio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Codigo_provincia', to='primer_app.provincia')),
            ],
        ),
    ]
